In [2]:
import numpy as np
from study_pytorch.perceptron import Perceptron

In [5]:
a = np.arange(3)
a

array([0, 1, 2])

In [6]:
b = np.arange(3, 6)
b

array([3, 4, 5])

In [7]:
a * b 

array([ 0,  4, 10])

In [8]:
import os
import pandas as pd

In [9]:
s =  "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
print("From URL:", s)

From URL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data


In [11]:
df = pd.read_csv(s, header=None, encoding="utf-8")
df.tail()

0    1    2    3               4
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica