## PyTorch でテンソルを作成する

In [1]:
import torch
import numpy as np

In [2]:
np.set_printoptions(precision=3)

In [3]:
a = [1,2,3]

In [4]:
b=np.array([4,5,6], dtype=np.int32)

In [5]:
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a.dtype, t_a,)
print(t_b.dtype, t_b)

torch.int64 tensor([1, 2, 3])
torch.int32 tensor([4, 5, 6], dtype=torch.int32)


In [6]:
t_ones = torch.ones(2, 3)
print(t_ones.shape, t_ones)

torch.Size([2, 3]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


## テンソルのデータ型と形状を操作する

In [7]:
# データ型の変更
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [8]:
# テンソルの天地
t = torch.rand(3,5)
t_tr = torch.transpose(t, 0,1)
print(t)
print(t_tr)

tensor([[0.0099, 0.2070, 0.6138, 0.3401, 0.8758],
        [0.1720, 0.9387, 0.1694, 0.9071, 0.8039],
        [0.3158, 0.7982, 0.2375, 0.2291, 0.6493]])
tensor([[0.0099, 0.1720, 0.3158],
        [0.2070, 0.9387, 0.7982],
        [0.6138, 0.1694, 0.2375],
        [0.3401, 0.9071, 0.2291],
        [0.8758, 0.8039, 0.6493]])


In [9]:
# テンソルの形状変更
t = torch.zeros(30)
t_reshape =t.reshape(5, 6)
print(t)
print(t_reshape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [10]:
# 不要な次元の削除
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t,2 )
print(t)
print(t_sqz)

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])
tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])


## テンソルでの算術計算

In [11]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) -1
t2 = torch.normal(mean=0, std=1, size=(5,2))
print(t1)
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [12]:
t3 = torch.multiply(t1, t2) # 要素ごとの積
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [13]:
t4 = torch.mean(t1, axis=0)  # 軸方向への平均を求める
print(t4)

tensor([-0.1373,  0.2028])


In [14]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))  # transpose で 5*2 行列に転置してから掛け算実施
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [15]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)  # transpose で 5*2 行列に転置してから掛け算実施
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [16]:
# テンソルの L^p ノルム
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


## テンソルの分割、積み上げ、連結

In [17]:
# 同じサイズでの分割
torch.manual_seed(1)
t = torch.rand(6)
print(t)

t_splits = torch.chunk(t,3)
for itm in t_splits:
    print(itm)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])
tensor([0.7576, 0.2793])
tensor([0.4031, 0.7347])
tensor([0.0293, 0.7999])


In [18]:
# 異なるサイズで分割
t = torch.rand(5)
print(t)

t_splits = torch.split(t,split_size_or_sections=[3,2])
for itm in t_splits:
    print(itm)

tensor([0.3971, 0.7544, 0.5695, 0.4388, 0.6387])
tensor([0.3971, 0.7544, 0.5695])
tensor([0.4388, 0.6387])


In [19]:
# 連結
A = torch.zeros(3)
B = torch.ones(2)
print(A, B)
C = torch.cat([A, B], axis = 0)
print(C)



tensor([0., 0., 0.]) tensor([1., 1.])
tensor([0., 0., 0., 1., 1.])


In [20]:
# 積み上げ
A = torch.zeros(3)
B = torch.ones(3)
print(A, B)
C = torch.stack([A, B], axis = 1)
print(C)

tensor([0., 0., 0.]) tensor([1., 1., 1.])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])


# PyTorch での入力パイプラインの構築
バッチごとに読み込む機能がある

## DataLoader を作成

In [21]:
from torch.utils.data import DataLoader
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)
print(data_loader)

In [22]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [23]:
data_loader = DataLoader(t,batch_size=3)

for item in data_loader:
    print(item)

tensor([0., 1., 2.])
tensor([3., 4., 5.])


## 二つのテンソルを一つのデータセットに結合する

In [24]:
torch.manual_seed(1)
t_x = torch.rand([4,3], dtype=torch.float32)
t_y = torch.arange(4)
print(t_x)
print(t_y)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])
tensor([0, 1, 2, 3])


In [25]:
from torch.utils.data import Dataset
class JointDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [26]:
joint_dataset = JointDataset(t_x, t_y)

In [27]:
for exapmle in joint_dataset:
    print(exapmle)

(tensor([0.7576, 0.2793, 0.4031]), tensor(0))
(tensor([0.7347, 0.0293, 0.7999]), tensor(1))
(tensor([0.3971, 0.7544, 0.5695]), tensor(2))
(tensor([0.4388, 0.6387, 0.5247]), tensor(3))


In [35]:
# シャッフル、バッチ、リピート
## バッチはもう↑でやった

data_loader = DataLoader(dataset=joint_dataset, batch_size=3, shuffle=True)
for i, batch in enumerate(data_loader, 1):
    print(i, batch)

1 [tensor([[0.4388, 0.6387, 0.5247],
        [0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]]), tensor([3, 0, 1])]
2 [tensor([[0.3971, 0.7544, 0.5695]]), tensor([2])]
